name: Run Cypress Project
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3 #uses key allows to use actions from github marketplace
      - name: Install NodeJS
        uses: actions/setup-node@v3 
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm ci # installs dependencies based on package-lock.json file
      - name: Run Tests
        run: npm run loginTest:Headless
        if: success() || failure()
      - name: Merge test results into one
        run: npm run mochawesome-merge
      - name: clean up files
        run: npm run prereport:mochawesome
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'nikkovasay'
          user_email: 'nikkovasay@gmail.com'
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Code
#         uses: actions/checkout@v3 #uses key allows to use actions from github marketplace
#       - name: Install NodeJS
#         uses: actions/setup-node@v3 
#         with:
#           node-version: 18
#       - name: Install Dependencies
#         run: npm ci # installs dependencies based on package-lock.json file
#       - name: Build Project
#         run: npm run build
#       - name: Deploy
#         run: echo "Deploying . . ."
